# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_pb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test_pb.proto',
  package='',
  serialized_pb=_b('\n\rtest_pb.proto\"0\n\x07student\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x0b\n\x03\x61ge\x18\x03 \x02(\x05\"$\n\x0b\x61ll_student\x12\x15\n\x03Stu\x18\x01 \x03(\x0b\x32\x08.student')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_STUDENT = _descriptor.Descriptor(
  name='student',
  full_name='student',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='student.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='student.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='age', full_name='student.age', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=65,
)


_ALL_STUDENT = _descriptor.Descriptor(
  name='all_student',
  full_name='all_student',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Stu', full_name='all_student.Stu', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=103,
)

_ALL_STUDENT.fields_by_name['Stu'].message_type = _STUDENT
DESCRIPTOR.message_types_by_name['student'] = _STUDENT
DESCRIPTOR.message_types_by_name['all_student'] = _ALL_STUDENT

student = _reflection.GeneratedProtocolMessageType('student', (_message.Message,), dict(
  DESCRIPTOR = _STUDENT,
  __module__ = 'test_pb_pb2'
  # @@protoc_insertion_point(class_scope:student)
  ))
_sym_db.RegisterMessage(student)

all_student = _reflection.GeneratedProtocolMessageType('all_student', (_message.Message,), dict(
  DESCRIPTOR = _ALL_STUDENT,
  __module__ = 'test_pb_pb2'
  # @@protoc_insertion_point(class_scope:all_student)
  ))
_sym_db.RegisterMessage(all_student)


# @@protoc_insertion_point(module_scope)
